apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metric-app-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: metric-app
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local:80
        metricName: demo_http_requests_total
        query: rate(demo_http_requests_total{method="GET", endpoint="/", job="metric-app"}[2m])
        threshold: "0.05"
