apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metric-app
  template:
    metadata:
      labels:
        app: metric-app
    spec:
      containers:
        - name: metric-app
          image: panthuya/metric-app:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: metric-app-service
spec:
  selector:
    app: metric-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
